[package]
name = "mvm"
version = "0.1.0"
edition = "2021"
authors = ["Maarten van Keulen maartenvKeulen@proton.me"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
